serverPort=5555
roundDurationMilliseconds=600000
sessionAutosaveSeconds=15
gamesFilePath=src/main/resources/data/games.json
playersFilePath=src/main/resources/data/players.json
gameStatesFilePath=src/main/resources/data/gameStates.json
gameRoundStateFilePath=src/main/resources/data/gameRoundState.json
